FROM python:3.11-slim
RUN apt-get update && apt-get install -y --no-install-recommends openjdk-21-jre-headless curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN pip install --no-cache-dir pyspark==3.5.1 delta-spark==3.2.0 kafka-python-ng==2.2.2 pandas numpy faker pyyaml python-dotenv sqlalchemy
